=== edenismine/graphs-in-telenetwork/resources/Network.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>
        <!-- ===========================================================================
        Network.dtd

        Contains the definition of an .xml file that represents a phone/video network
        made up of a non-empty set of stations, and links between them. A network is
        a connected graph, so all stations must be linked. The number of stations and
        links are given as attributes.
        ============================================================================= -->

        <!ELEMENT Network (Station+, Link*)>
        <!ATTLIST Network stations CDATA #REQUIRED>
        <!ATTLIST Network links CDATA #REQUIRED>

        <!-- A station has a set of clients, and its attributes
        are the station's name, name, and its unique area code, code. -->

        <!ELEMENT Station (Client*)>
        <!ATTLIST Station name CDATA #REQUIRED>
        <!ATTLIST Station code CDATA #REQUIRED>

        <!-- A client can be an empty element whose attributes
        are the clients name, name, and the clients phone number, phone. -->

        <!ELEMENT Client EMPTY>
        <!ATTLIST Client name CDATA #REQUIRED>
        <!ATTLIST Client phone CDATA #REQUIRED>

        <!-- A link can be an empty element whose attributes
        are the are codes of the two stations that it links. -->

        <!ELEMENT Link EMPTY>
        <!ATTLIST Link stationACode CDATA #REQUIRED>
        <!ATTLIST Link stationBCode CDATA #REQUIRED>

=== edenismine/graphs-in-telenetwork/resources/network.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Network SYSTEM "Network.dtd">
<Network stations="5" links="4">
    <Station name="Ciudad de Mexico" code="1">
        <Client name="Carlos" phone="56581111"/>
        <Client name="Joaquin" phone="55667788"/>
    </Station>

    <Station name="Morelia" code="2">
        <Client name="Pedro" phone="55771122"/>
    </Station>

    <Station name="Cuernavaca" code="3">
        <Client name="RaÃºl" phone="55443322"/>
    </Station>

    <Station name="Pachuca" code="4">
        <Client name="Luis" phone="11223311"/>
    </Station>

    <Station name="Tlaxcala" code="5">
        <Client name="Juan" phone="55443322"/>
    </Station>

    <Link stationACode="1" stationBCode="2"/>

    <Link stationACode="2" stationBCode="4"/>

    <Link stationACode="4" stationBCode="5"/>

    <Link stationACode="3" stationBCode="1"/>

</Network>
